version: "3.9"
services:
  backend:
    build:
      context: .
    env_file:
      - ./.env
    environment:
      PYTHON_SERVICE_URL: http://python_worker:8000
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - python_worker
    ports:
      - "4000:4000"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    depends_on:
      - backend
    environment:
      # Optional: set your email for Let's Encrypt rate-limit friendliness.
      ACME_AGREE: "true"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  python_worker:
    build:
      context: ../python-worker
    env_file:
      - ../python-worker/.env
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    expose:
      - "8000"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    expose:
      - "6379"
    restart: unless-stopped

networks:
  default:
    name: layer1_internal
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
